### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by blelump** [jolocom/keriox#15]
Hi @chunningham . I don't have any other contact to you so I'm writing here. I'm working along with @edytapawlak to make this world great again :wink:  . I'd like to ask what's your current plan / approach to tackle KERI implementation in Rust so we can align with the steps in what areas we could help each other to get something meaningful. So basically what you're planning in the short term / which part you'd continue with and in which we could join.

**Comment by chunningham** [comment]
Hey @blelump! Now that the code has been [contributed to DIF](https://github.com/decentralized-identity/keriox/pull/13), we can start planning the work there together moving forward. If you have any preference for project/task management I am open to suggestions, else I figure the github project management tool should suffice for now. There is a [weekly DIF call for KERI](https://docs.google.com/document/d/1UVgMKGOjU_5bbgZH2WazNxUMRI0ucwDISrixd8WFxYc/edit?ts=5f034380#heading=h.ysvyy772yybd) where roadmapping and such is discussed which you can attend if you have signed the IPR agreement (I believe HCF has but not sure if that covers all members of the org)
The next areas of work will probably be:
- documentation and testing
- database functionality
- rotation event implementation
- witnesses
- more ergonomic APIs/some refactoring

generally I'm reachable in the DIF slack, or you can email me at charles@jolocom.io
looking forward to your input :muscle:
